# Variables

@baseUrl = http://localhost:3333

# Health check

GET {{baseUrl}}/health

###

# Get rooms

GET {{baseUrl}}/rooms

###

# Create room
# @name createRoom

POST {{baseUrl}}/rooms
Content-Type: application/json

{
    "name": "Test room",
    "description": "This is a test room"
}

###

@roomId = {{createRoom.response.body.$.roomId}}

###

# Get room questions
# @name getRoomQuestions

GET {{baseUrl}}/rooms/{{roomId}}/questions

###

# Create Question
# @name createQuestion

POST {{baseUrl}}/rooms/{{roomId}}/question
Content-Type: application/json

{
    "question": "What is React?"
}